### ISSUE TITLE
Undefined method "run"

### ISSUE THREAD

**Issue by kd75000** [roach-php/laravel#1]
I installed roach-php/laravel package and I generated php artisan roach:spider LaravelDocsSpider as doc says.
When I call Roach::run(LaravelDocsSpider::class), there is the following error : Undefined method "run".

**Comment by ksassnowski** [comment]
Sorry, this is a documentation error. Someone already opened a [PR](https://github.com/roach-php/roach-php.dev/pull/2) on the documentation repository. The correct method is `Roach::startSpider`

**Comment by kd75000** [comment]
Thanks ! Great package by the way
