### ISSUE TITLE
Click on button instead of link to process the next page

### ISSUE THREAD

**Issue by iamkarsoft** [roach-php/laravel#12]
I've been able to scrape the first page. But the next button isn't a link with an a tag. It's a button instead. I'm unable to proceed to the next page with using `links()`. is there any other way to achieve navigating to the next page to process when it's a button instead?

**Comment by ksassnowski** [comment]
I'm afraid not as this would be out of scope for a web scraper. If you need to actually interact with the page, something like Laravel Dusk might be better suited for your purpose.
