### ISSUE TITLE
Dynamic Middleware

### ISSUE THREAD

**Issue by dilab** [roach-php/laravel#13]
How do I dynamically enable/disable a Middleware?

This is useful when crawling a series of pages. e.g. page A is a normal HTML page with needs the ExecuteJavascriptMiddleware Middleware and, page B is an ajax page, which has to ignore the ExecuteJavascriptMiddleware Middleware.

**Comment by ksassnowski** [comment]
There's currently no way to do this as all middleware gets applied to all requests. For your particular example, running the `ExecuteJavascriptMiddleware` on pages that don't require it still works, however. It might be a little slower, though.

**Comment by dilab** [comment]
Thanks for the clarification.
