### ISSUE TITLE
The console doesn't output anything

### ISSUE THREAD

**Issue by LittleHans8** [roach-php/laravel#14]
I plan to print some logs, but there is no output. 

Environment：Win11; PHPStorm
![image](https://user-images.githubusercontent.com/15800501/172837881-7ffc621f-8b64-465b-bbbe-aa4387ac18d4.png)

But when I try to run the same code on macos ,it works:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/15800501/173049734-75984b7b-ac73-49a2-b734-94ee6ec6c931.png">

**Comment by AkioSarkiz** [comment]
I think you should test the site on the Linux/macos side

**Comment by ksassnowski** [comment]
This is because Roach uses the logging configuration of your Laravel app for its logger. So it will probably log to your `laravel.log` file. The easiest way to get the output in your terminal is to temporarily change your `LOG_CHANNEL` environment variable to `stderr` before running the spider.

```
LOG_CHANNEL=stderr php artisan roach:run MySpider
```
