### ISSUE TITLE
Listening to events fired by Roach

### ISSUE THREAD

**Issue by dodomedia** [roach-php/laravel#16]
I was not able listening to any of the fired events through the Laravel event system. I tried it using the class name (for example `RunFinished::class`) and by using the internal name (`RunFinished::NAME`), but both times the listener won't get called. Is this currently not supported or am I doing something wrong? If so, can you provide an example for listening to Roach events through Laravel?

**Comment by ksassnowski** [comment]
The events don't get dispatched through Laravel's event system (although that is something that could potentially be changed in the future). Events are used by [extensions](https://roach-php.dev/docs/extensions/), so in order to listen on them, you will have to implement your own extension.
