### ISSUE TITLE
Target [Psr\Container\ContainerInterface] is not instantiable while building [RoachPHP\Core\Runner]

### ISSUE THREAD

**Issue by angelcoding** [roach-php/laravel#17]
If I run `php artisan roach:run MySpider` I get: 
```
Target [Psr\Container\ContainerInterface] is not instantiable while building [RoachPHP\Core\Runner].
```

Adding the following to `\RoachPHP\Laravel\RoachServiceProvider::registeringPackage()` seems to fix it.
```
$this->app->bind(\Psr\Container\ContainerInterface::class, \RoachPHP\Core\DefaultContainer::class);
```
Is it possible to get this updated please (assuming that's the correct fix)?

**Comment by ksassnowski** [comment]
I'm unable to reproduce this issue on a fresh Laravel installation. Can you provide a repository that reproduces this error?

**Comment by angelcoding** [comment]
Hmm. I'm using October CMS v3 which is built on Laravel 9. I guess there's a difference in the application config or something compared to the Laravel default. I'm no expert on this part of Laravel tbh.

No worries, I can add the binding in my own code and that seems to work too. Thanks for your time.
