### ISSUE TITLE
Not support Laravel 10

### ISSUE THREAD

**Issue by bassem-shoukry** [roach-php/laravel#22]
Problem 1
    - roach-php/laravel 0.1.0 requires roach-php/core ^0.1.0 -> satisfiable by roach-php/core[0.1.0].
    - roach-php/laravel[0.2.0, ..., 0.2.1] require roach-php/core ^0.2.0 -> satisfiable by roach-php/core[0.2.0].
    - roach-php/laravel[0.3.0, ..., 0.3.1] require roach-php/core ^0.3.0 -> satisfiable by roach-php/core[0.3.0].
    - roach-php/laravel 2.0.0 requires roach-php/core ^1.0 || ^2.0 -> satisfiable by roach-php/core[1.0.0, 1.1.0, 1.1.1, 1.1.2, 2.0.0, 2.0.1].
    - roach-php/core[0.1.0, ..., 0.3.0, 1.0.0, ..., 1.1.2] require monolog/monolog ^2.3 -> found monolog/monolog[2.3.0, ..., 2.9.2] but the package is fixed to 3.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - roach-php/laravel 1.0.0 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^10.0).
    - roach-php/core 2.0.0 requires sebastian/version ^3.0 -> found sebastian/version[3.0.0, 3.0.1, 3.0.2] but the package is fixed to 4.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - roach-php/core 2.0.1 requires symfony/css-selector ^6.0 -> found symfony/css-selector[v6.0.0, ..., v6.4.0] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires roach-php/laravel * -> satisfiable by roach-php/laravel[0.1.0, ..., 0.3.1, 1.0.0, 2.0.0].

**Comment by xewl** [comment]
By now:
`composer require roach-php/laravel -W`
`composer require roach-php/laravel:"3.0"`

**Comment by ksassnowski** [comment]
Yeah, the `-W` is required for now. I'm working on fixing that but updating the dependencies has a bunch of knock-on effects that I haven't gotten around to yet.

**Comment by RalpinMcDjango** [comment]
> Yeah, the `-W` is required for now. I'm working on fixing that but updating the dependencies has a bunch of knock-on effects that I haven't gotten around to yet.

Great news i look forward to this getting resolved :)

**Comment by bassem-shoukry** [comment]
Thanks, it’s working now!
