### ISSUE TITLE
Target [RoachPHP\Scheduling\RequestSchedulerInterface] is not instantiable while building [RoachPHP\Core\Engine].

### ISSUE THREAD

**Issue by mohamedsabil83** [roach-php/laravel#5]
I just trying this package to start using it in my new project.

When use `Roach::startSpider(DataSpider::class)`, it returns the error mentioned in the title.

**Comment by ksassnowski** [comment]
I’m pretty sure it’s because you forgot to publish the config. https://roach-php.dev/docs/laravel#installing-the-laravel-adapter

There’s something wrong with the way the default config gets merged if the user didn’t publish the config.

**Comment by mohamedsabil83** [comment]
Yes, that's the problem. In docs, the sound looks like publishing the config is optional.

Is it able to filter using **class name** or just **html tags**?
Also, is there a discord or similar for **roach** to discuss?

**Comment by mohamedsabil83** [comment]
> Is it able to filter using **class name** or just **html tags**?

Yes, it is.

> Also, is there a discord or similar for **roach** to discuss?

if there, please mention me. I'll close it now

**Comment by zepfietje** [comment]
I also ran into this.
Like @mohamedsabil83 said, from the docs it looks like publishing the config is optional.

**Comment by ksassnowski** [comment]
FYI, this problem has been fixed in the [0.3.1 release](https://github.com/roach-php/laravel/compare/0.3.0...0.3.1). Publishing the config should now be _truly_ optional.
