### ISSUE TITLE
A massive amount of roach spiders would play well together via Laravel Horizon?

### ISSUE THREAD

**Issue by osthafen** [roach-php/laravel#7]
Hi Kai,
For the use of a massive amount of spiders (each crawling a complete website ) - would this package play well together with Laravel Horizon and Redis queues?
Thanks a lot
Martin

**Comment by ksassnowski** [comment]
I don’t see why it wouldn’t. You’d dispatch a bunch of jobs that each basically just run `Roach::startSpider(....)`. As long as each of these runs don’t take hours, you should be fine.
